name: Build AppImage

on:
  - workflow_dispatch

env: 
  APPDIR: AdvancedSettings.AppDir

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        # Install build tools
        sudo apt-get -y install build-essential libgl1-mesa-dev qt5-default qtmultimedia5-dev libqt5multimediawidgets5 libqt5multimedia5-plugins libqt5multimedia5 qml-module-qtquick-extras qml-module-qtquick-controls2 qml-module-qtquick-dialogs qml-module-qt-websockets qml-module-qtmultimedia qtdeclarative5-dev qtchooser libqt5websockets5-dev qtwayland5 qtwayland5-dev-tools libwayland-dev libgles2-mesa-dev libxkbcommon-dev libqt5waylandclient5-dev qml-module-qtwayland-compositor
        export QT_SELECT=5

        test -d ${APPDIR} && rm -rf ${APPDIR}
        mkdir -p ${APPDIR}/usr/lib

        # Compile
        qmake PREFIX=${APPDIR}/usr CONFIG+=noX11 CONFIG+=noDBUS CONFIG+=noPulse
        make
        make install

        mv ${APPDIR}/usr/AdvancedSettings ${APPDIR}/usr/bin
        chmod +x ${APPDIR}/usr/bin/AdvancedSettings
        find ${APPDIR}
    - name: Package AppImage
      run: |
        export QT_SELECT=5

        mkdir -p ${APPDIR}/usr/share/applications/
        cp AppRun.desktop ${APPDIR}/usr/share/applications/AdvancedSettings.desktop
        mkdir -p ${APPDIR}/usr/share/icons/hicolor/256x256/
        cp AdvancedSettings.png ${APPDIR}/usr/share/icons/hicolor/256x256/

        test -f linuxdeployqt-continuous-x86_64.AppImage || wget -q "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
        chmod +x linuxdeployqt-continuous-x86_64.AppImage
        export VERSION=Wayland
        ./linuxdeployqt-continuous-x86_64.AppImage ${APPDIR}/usr/share/applications/AdvancedSettings.desktop -extra-plugins=platforms/libqwayland-egl.so,platforms/libqwayland-generic.so -appimage
        find ${APPDIR}
    - name: Upload AppImage
      uses: actions/upload-artifact@v3
      with:
        path: ./OpenVR_Advanced_Settings-Wayland-x86_64.AppImage
        name: OpenVR-AdvancedSettings-Wayland-x86_64.AppImage
